### PR TITLE
Change project structure

### PR DESCRIPTION
**Pull request by Indoxer**

### CODE REVIEW

**Review by aruzo1 — APPROVED** [review]

**Comment by Indoxer** [comment]
Aruzo made spaghetti in changes. I will repair this later.

**Comment by aruzo1** [comment]
> Aruzo made great commits in changes. I will repair this later.

Reverted to your working code

**Comment by Indoxer** [comment]
I repaired github ci and fixed commits history. (I did hard reset to my changes)

**Comment by Indoxer** [comment]
At this moment everything look good to me. However, for no reason tests coverage is down by 0.7%.

**Pull request merged**
